#!/bin/sh

# nshmp-haz-ws pre-build repository update. Script reads 'update.properties'
# for git tags and updates repositories accordingly. Script should be run
# from the root of the nshmp-haz-ws repository. Note that it is possible for
# this script to revert the nshmp-haz-ws repository to a version that
# predates this script. Checkout master to revert. Note also that the script
# leaves all repositories in a 'detached HEAD' state.

VERSIONS_FILE=update.properties

# Find the first match in the props file, cut the version out, and trim
# the trailing carriage return
function getProperty {
   PROP_KEY=$1
   PROP_VALUE=`cat $VERSIONS_FILE | grep "$PROP_KEY" -m1 | cut -d'=' -f2 | tr -d '\r'`
   echo $PROP_VALUE
}

function gitPull {
    cd $1
    echo
    echo
    echo "Processing: "$1 $2
    echo "----> checkout master"
    git checkout master
    echo "----> pull upstream master --tags"
    git pull upstream master --tags
    echo "----> checkout tags/$2"
    git checkout $2
}

echo "Reading tags from $VERSIONS_FILE"

NSHMP_HAZ_VERSION=$(getProperty "nshmp-haz")
echo "  nshmp-haz:      $NSHMP_HAZ_VERSION"

NSHMP_HAZ_WS_VERSION=$(getProperty "nshmp-haz-ws")
echo "  nshmp-haz-ws:   $NSHMP_HAZ_WS_VERSION"

NSHM_COUS_2008_VERSION=$(getProperty "nshm-cous-2008")
echo "  nshm-cous-2008: $NSHM_COUS_2008_VERSION"

NSHM_COUS_2014_VERSION=$(getProperty "nshm-cous-2014")
echo "  nshm-cous-2014: $NSHM_COUS_2014_VERSION"

NSHM_AK_2007_VERSION=$(getProperty "nshm-ak-2007")
echo "  nshm-ak-2007:   $NSHM_AK_2007_VERSION"


dir=`pwd`

gitPull ../nshmp-haz       $NSHMP_HAZ_VERSION
gitPull ../nshmp-haz-ws    $NSHMP_HAZ_WS_VERSION
gitPull ../nshm-cous-2008  $NSHM_COUS_2008_VERSION
gitPull ../nshm-cous-2014  $NSHM_COUS_2014_VERSION
gitPull ../nshm-ak-2007    $NSHM_AK_2007_VERSION

cd $dir
